apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  OTEL_SERVICE_NAME: "testtf"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.monitoring:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=default"
  SERVER_ADDRESS: "0.0.0.0"
  SERVER_PORT: "8081"
  ENVIRONMENT: "production"
  PYROSCOPE_ENABLED: "true"
  PYROSCOPE_ENDPOINT: "http://pyroscope.monitoring:4040"
